name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # You can change this to your desired PHP version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # You can change this to your desired Node.js version

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Install Node.js dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Create .env file
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" > .env
          echo "DEFAULT_LANGUAGE=${{ secrets.DEFAULT_LANGUAGE }}" >> .env
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env
          echo "APP_ENV=production" >> .env

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            assets/**
            .github/**
            src/**
            .env.example
            README.md
            composer.json
            composer.lock
            package.json
            package-lock.json
            vite.config.js 